#!/usr/bin/env bash
# This script first updates the package index and installs nginx. Then it creates an HTML file with the content "Hello World!" in the nginx default web directory.

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
