#!/usr/bin/env bash
# This script installs nginx. Then it configures it on a remote server

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx start
