#!/usr/bin/env bash
# Customazing a 404-error page

apt-get update
apt-get -y intall nginx
sudo afw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
SERVER_CONFIG="\\n\\tlocation /redirect_me {\\n\\t\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\\t}"
ERROR_PAGE="\\n\\terror_page 404 /404.html;"
sudo sed -i "/server_name _;/a\\$SERVER_CONFIG" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a\\$ERROR_PAGE" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
