#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

# Update package repository
apt-get update

# Install nginx and allow HTTP traffic
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# Create Index and 404 erro pages
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx
SERVER_CONFIG="\\n\\tlocation /redirect_me {\\n\\t\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\\t}"
ERROR_PAGE="\\n\\terror_page 404 /404.html;"
CUSTOM_HEADER="\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
FILE_PATH="/etc/nginx/sites-available/default"
sed -i "/server_name _;/a\\$SERVER_CONFIG" "$FILE_PATH"
sed -i "/server_name _;/a\\$ERROR_PAGE" "$FILE_PATH"
sed -i "/server_name _;/a\\$CUSTOM_HEADER" "$FILE_PATH"

# Restart nginx service
service nginx restart
