#!/usr/bin/env bash
# Installs and setup haproxy


# Install HAproxy
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

# Configure HAproxy
FRONTEND="\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back"
BACKEND="\nbackend http_back\n\tbalance roundrobin\n\tserver 440517-web-01 100.26.172.45:80 check\n\tserver 440517-web-02 54.236.12.243:80 check"
FILE_PATH="/etc/haproxy/haproxy.cfg"
echo -e "$FRONTEND" | sudo tee -a $FILE_PATH
echo -e "$BACKEND" | sudo tee -a $FILE_PATH

# Reload HAproxy service
systemctl reload haproxy
