#!/usr/bin/env bash
# Installs and setup haproxy


# Update repo
apt-get -y update

# Install HAproxy
apt-get install -y haproxy

# Configure HAproxy
echo '
frontend http_front
        bind 0:80
        default_backend http_back

backend http_back
        balance roundrobin
        server 440517-web-01 100.26.172.45:80 check
        server 440517-web-02 54.236.12.243:80 check
' >> /etc/haproxy/haproxy.cfg

# Reload HAproxy service
service haproxy restart
