#!/usr/bin/env bash
# Create a backup of all MySQL databases and compress it.

# MySQL root password
MYSQL_ROOT_PASSWORD=$1

# Create a MySQL dump of all databases
mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > backup.sql

# Get the current date in day-month-year format
CURRENT_DATE=$(date +%d-%m-%Y)

# Create a compressed archive of the MySQL dump
tar -czvf "$CURRENT_DATE.tar.gz" backup.sql
