#!/usr/bin/env bash
# Script to run Nginx as the nginx user and listen on port 8080

# Ensure nginx is not running
sudo pkill nginx

# Update the nginx.conf file to use the nginx user and listen on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# change permission
sudo chmod 644 /etc/nginx/nginx.conf

# Start nginx as the nginx user
sudo -u nginx service nginx start
